# Generated by Django 2.1.1 on 2018-09-29 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_next',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_next',
            field=models.CharField(max_length=255),
        ),
    ]
